# Generated by Django 4.2.7 on 2023-11-28 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_department_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='permanent_address',
        ),
        migrations.RemoveField(
            model_name='student',
            name='present_address',
        ),
        migrations.RemoveField(
            model_name='student',
            name='session_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_id',
        ),
    ]
