# Generated by Django 4.2.7 on 2023-11-28 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_student_address_student_session_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
