# Generated by Django 4.2.7 on 2023-11-29 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='hod_name',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
