# Generated by Django 4.2.7 on 2023-11-29 04:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_department_hod_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
