# Generated by Django 4.2.7 on 2023-12-03 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_stuff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stuff_Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stuff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.stuff')),
            ],
        ),
    ]
