# Generated by Django 4.2.7 on 2023-12-04 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_stuff_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuff_notification',
            name='status',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
