# Generated by Django 4.2.7 on 2023-12-04 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_rename_data_stuff_leave_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stuff_leave',
            old_name='staff_id',
            new_name='stuff_id',
        ),
    ]
