# Generated by Django 4.2.7 on 2023-12-06 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_course_department_id_alter_course_stuff_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='department_id',
        ),
        migrations.RemoveField(
            model_name='course',
            name='stuff_id',
        ),
    ]
