# Generated by Django 4.2.7 on 2023-12-06 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_course_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stuff',
            name='admin',
        ),
    ]
