# Generated by Django 4.2.7 on 2023-12-07 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_student_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stuff',
            name='admin',
        ),
    ]
