# Generated by Django 4.2.7 on 2023-12-08 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_attendance_attendance_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_rid',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
