# Generated by Django 4.2.7 on 2023-12-09 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_student_student_rid'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance_report',
            name='status',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
