# Generated by Django 4.2.7 on 2023-12-11 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_attendance_report_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuff_leave',
            name='mfile',
            field=models.FileField(null=True, upload_to='media/leave_file'),
        ),
        migrations.AlterField(
            model_name='stuff_leave',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
